name: Docker Image CI

on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: @weekly

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t tkp1n/node-ci:$(date +%y%m%d) -t tkp1n/node-ci:latest .
